import PropTypes from "prop-types";

export const types = {
  data: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.array, PropTypes.number])),
  labels: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number])),
  diameter: PropTypes.number,
  strokeWidth: PropTypes.number,
  colors: PropTypes.arrayOf(PropTypes.string),
  fill: PropTypes.string,
  responsive: PropTypes.bool,
  tooltips: PropTypes.bool,
  textProps: PropTypes.object,
  precision: PropTypes.number,
  tooltip: PropTypes.bool,
  style: PropTypes.object,
  className: PropTypes.string,
  classNamePrefix: PropTypes.string,
  percentages: PropTypes.bool,
  prefix: PropTypes.string,
  interactiveLegend: PropTypes.bool,
  // pie
  offset: PropTypes.number,
  offsetColor: PropTypes.string,
  // bar and line
  interactiveBars: PropTypes.bool,
  height: PropTypes.number,
  yScaleWidth: PropTypes.number,
  tooltipPrefix: PropTypes.string,
  tooltipHeight: PropTypes.number,
  multiColors: PropTypes.bool,
  yMinTicks: PropTypes.number,
  xScaleHeight: PropTypes.number,
  tickColor: PropTypes.string,
  barContainerWidth: PropTypes.number,
  barWidth: PropTypes.number,
  // line
  lineWidth: PropTypes.number,
  sectionWidth: PropTypes.number,
  centering: PropTypes.bool,
  pointSize: PropTypes.number,
  pointBorderWidth: PropTypes.number,
  pointBorderColor: PropTypes.string,
  trapezoid: PropTypes.bool,
  trapezeStrokeWidth: PropTypes.number,
  trapezeStrokeColor: PropTypes.string,
  trapezeFill: PropTypes.string,
};
